# Generated by Django 4.2.30 on 2026-04-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_rename_cita_to_citaservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citaservicio',
            options={'verbose_name': 'cita de servicio', 'verbose_name_plural': 'citas de servicio'},
        ),
    ]
