# Generated by Django 4.2.30 on 2026-04-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_encargado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('admin', 'Administrador'), ('encargado', 'Encargado de Taller')], default='cliente', max_length=10),
        ),
    ]
